### ISSUE TITLE
Any update on the roadmap?

### ISSUE THREAD

**Issue by tez1szh** [eclipse-cyclonedds/cyclonedds#1620]
The [current roadmap was updated 2 years ago](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/ROADMAP.md), any  update?

- which of the features are already implemented?
- what's the next step and expected release date?
- ...

**Comment by eboasson** [comment]
Hi @tez1szh, I had completely forgotten about that list. 2 years indeed ... following that document:

### Short-term milestones

#### Cyclone 0.8

- [x] C++11 APIs (GA)
- [x] New APIs to access to serialized CDR data
- [x] New APIs for configuring the deployment of Cyclone DDS based application
- [x] Multi-Network interface cards support (Consolidation) — this is something that can always be improved upon, and some ideas have gestated by now
- [x] Content filtering support for C++
- [x] IDL compiler front-end & back end support of the Xtypes annotations
- [x] Topic and data type discovery
- [x] ROS 2 Quality Level 2

#### Cyclone 0.9

- [ ] Integration of Durability Service for Transient and Persistent data — delayed, but now finally properly in-progress
- [x] Shared memory transport support
- [x] Python APIs (GA): done
- [ ] Internet-scale deployment support — partial: we use the [Zenoh](https://zenoh.io) DDS bridge for this, but there are currently some limitations that make me hesitant to claim it is done
- [x] DDS-Xtypes APIs
- [x] Asynchronous mode of operation — arguably implemented, but there are some improvements that I really want
- [ ] ROS 2 Quality Level 1 — not yet, but the issue is paperwork and there's progress on that front

The mid-term and long-term milestones listed in the document haven't been done yet, although those related to use in certified or real-time contexts (e.g., no discovery, no-memory-allocation-after-initialisation) are in-progress and/or have been demonstrated already (e.g., TSN support, if not yet the configuration formats defined by DDS-TSN). At the moment a lot of effort is going into work related to safety certification and that means not much magic has been happening in terms of new features.

For the next release I was waiting for the API for dynamically constructing types to get added, and now that that's done, I think I should start the paperwork to get a fresh release review by the Eclipse Foundation.

As discussed on our Discord, the plan is to drop the `0.` prefix from the version number, and so go from 0.10 to 11.0. We stuck to major version 0 for all these years because of an expectation of breaking the API and not wanting to bump it without cause, but we have now figured out a way to do what we want to do without breaking the API. That would mean we'd be stuck with major version 0 for another few years, and that "gets boring".

I expect I'll create a branch for this release in the short term, but the actual release tag will probably take a while.
